security:

    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        App\Entity\User: sha512

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: ~ }
        database:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #api_doc:
        #    pattern: ^/
        #    anonymous: ~


        main:
            pattern: ^/api/auth
            anonymous: ~
            access_denied_handler: App\Security\Authorization\AccessDeniedHandler

        api:
            pattern: ^/api/
            stateless: true
            provider: database
            guard:
                authenticators:
                - App\Security\Authentication\ApiTokenAuthenticator

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/*, roles: ROLE_USER }
        # - { path: ^/api/user, roles: ROLE_USER }
        # - { path: ^/api/schools, roles: ROLE_USER }
        # - { path: ^/api/classes, roles: ROLE_USER }
        # - { path: ^/profile, roles: ROLE_USER }
