childrens:
    type: rest
    resource: App\Controller\ChildrenController

classes:
    type: rest
    resource: App\Controller\SchoolClassController

parents:
    type: rest
    resource: App\Controller\UserParentController

teacher:
    type: rest
    resource: App\Controller\UserTeacherController

actions:
    type: rest
    resource: App\Controller\ActionController

schoolLevels:
    type: rest
    resource: App\Controller\SchoolLevelController

users:
    type: rest
    resource: App\Controller\UserController

admin:
    type: rest
    resource: App\Controller\AdminController