childrens:
    type: rest
    resource: App\Controller\ChildrenController

classes:
    type: rest
    resource: App\Controller\SchoolClassController

parents:
    type: rest
    resource: App\Controller\UserParentController

teacher:
    type: rest
    resource: App\Controller\UserTeacherController