# Api Doc route

api:
    type: rest
    resource: 'routes_api.yaml'
    prefix: api

app.swagger_ui:
  path: /
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# Api Route
#auth:
#    type: rest
#    resource: App\Controller\AuthController

#create
#login

  #index:
  #    path: /
  #    controller: App\Controller\DefaultController::index
